BRANCHES_TO_OPEN:
  - pid
  - p_x
  - p_y
  - p_z
  - p
  - status
  - v_x
  - v_y
  - v_z
  - theta
  - phi
  - sector
  - NDF
  - chi2
  - E_PCAL
  - E_ECIN
  - E_ECOUT
  - PCAL_U
  - PCAL_V
  - PCAL_W
  - DC_region1_x
  - DC_region1_y
  - DC_region1_z
  - DC_region1_edge
  - DC_region2_x
  - DC_region2_y
  - DC_region2_z
  - DC_region2_edge
  - DC_region3_x
  - DC_region3_y
  - DC_region3_z
  - DC_region3_edge

BRANCHES_TO_SAVE:
  - pid
  - p_x
  - p_y
  - p_z
  - p
  - status
  - v_x
  - v_y
  - v_z
  - theta
  - phi
  - sector
  - NDF
  - chi2
  - E_PCAL
  - E_ECIN
  - E_ECOUT
  - PCAL_U
  - PCAL_V
  - PCAL_W
  - DC_region1_x
  - DC_region1_y
  - DC_region1_z
  - DC_region1_edge
  - DC_region2_x
  - DC_region2_y
  - DC_region2_z
  - DC_region2_edge
  - DC_region3_x
  - DC_region3_y
  - DC_region3_z
  - DC_region3_edge
  - Q2
  - nu
  - x
  - y
  - W

MC_BRANCHES_TO_OPEN:
  - MC_pid
  - MC_px
  - MC_py
  - MC_pz
  - MC_vx
  - MC_vy
  - MC_vz

MC_BRANCHES_TO_SAVE:
  - MC_pid
  - MC_px
  - MC_py
  - MC_pz
  - MC_vx
  - MC_vy
  - MC_vz
  - MC_theta
  - MC_phi
  - MC_Q2
  - MC_nu
  - MC_x
  - MC_y
  - MC_W
